/* ================================================
   Park Tycoon – Attraction Configuration
   Edit this file to add/tweak attractions.
   Each entry is easily configurable:
     - id:          unique numeric key (0-63)
     - name:        display name
     - footprint:   { w, h } in tiles
     - buildPrice:  cost to place
     - ticketPrice: per-ride income (configurable at runtime too)
     - capacity:    max simultaneous riders
     - category:    "fun" | "thrill" | "relax"
     - appeal:      0-100 attractiveness score
     - rideTicks:   simulation ticks per ride cycle
     - color:       hex fill for pixel sprite
     - icon:        emoji shorthand shown on HUD
   ================================================ */

export interface AttractionDef {
  id: number;
  name: string;
  footprint: { w: number; h: number };
  buildPrice: number;
  monthlyOperatingCost: number;
  ticketPrice: number;
  capacity: number;
  category: 'fun' | 'thrill' | 'relax' | 'food' | 'drink' | 'toilet';
  appeal: number;
  requiredExcitement: number;
  rideTicks: number;
  nauseaGain: number;
  color: string;
  icon: string;
  spriteUrl?: string;
}

const ATTRACTIONS: AttractionDef[] = [
  {
    id: 0,
    name: 'Carousel',
    footprint: { w: 2, h: 2 },
    buildPrice: 500,
    monthlyOperatingCost: 60,
    ticketPrice: 3,
    capacity: 8,
    category: 'fun',
    appeal: 60,
    requiredExcitement: 10,
    rideTicks: 40,
    nauseaGain: 6,
    color: '#e74c3c',
    icon: '🎠',
  },
  {
    id: 1,
    name: 'Roller Coaster',
    footprint: { w: 1, h: 1 },
    buildPrice: 2000,
    monthlyOperatingCost: 220,
    ticketPrice: 8,
    capacity: 12,
    category: 'thrill',
    appeal: 90,
    requiredExcitement: 55,
    rideTicks: 60,
    nauseaGain: 22,
    color: '#e67e22',
    icon: '🎢',
  },
  {
    id: 2,
    name: 'Ferris Wheel',
    footprint: { w: 3, h: 3 },
    buildPrice: 1200,
    monthlyOperatingCost: 110,
    ticketPrice: 5,
    capacity: 16,
    category: 'relax',
    appeal: 75,
    requiredExcitement: 15,
    rideTicks: 50,
    nauseaGain: 4,
    color: '#3498db',
    icon: '🎡',
  },
  {
    id: 3,
    name: 'Bumper Cars',
    footprint: { w: 3, h: 2 },
    buildPrice: 800,
    monthlyOperatingCost: 85,
    ticketPrice: 4,
    capacity: 10,
    category: 'fun',
    appeal: 65,
    requiredExcitement: 20,
    rideTicks: 35,
    nauseaGain: 10,
    color: '#f1c40f',
    icon: '🚗',
  },
  {
    id: 4,
    name: 'Haunted House',
    footprint: { w: 3, h: 3 },
    buildPrice: 1500,
    monthlyOperatingCost: 150,
    ticketPrice: 6,
    capacity: 6,
    category: 'thrill',
    appeal: 80,
    requiredExcitement: 45,
    rideTicks: 55,
    nauseaGain: 12,
    color: '#8e44ad',
    icon: '👻',
  },
  {
    id: 5,
    name: 'Tea Cups',
    footprint: { w: 2, h: 2 },
    buildPrice: 400,
    monthlyOperatingCost: 40,
    ticketPrice: 2,
    capacity: 8,
    category: 'fun',
    appeal: 50,
    requiredExcitement: 10,
    rideTicks: 30,
    nauseaGain: 14,
    color: '#1abc9c',
    icon: '🍵',
  },
  {
    id: 6,
    name: 'Log Flume',
    footprint: { w: 1, h: 1 },
    buildPrice: 1200,
    monthlyOperatingCost: 170,
    ticketPrice: 7,
    capacity: 8,
    category: 'thrill',
    appeal: 85,
    requiredExcitement: 50,
    rideTicks: 45,
    nauseaGain: 18,
    color: '#2980b9',
    icon: '🚣',
  },
  {
    id: 7,
    name: 'Zen Garden',
    footprint: { w: 2, h: 3 },
    buildPrice: 600,
    monthlyOperatingCost: 45,
    ticketPrice: 2,
    capacity: 20,
    category: 'relax',
    appeal: 55,
    requiredExcitement: 0,
    rideTicks: 40,
    nauseaGain: 0,
    color: '#27ae60',
    icon: '🌸',
  },
  {
    id: 14,
    name: 'Balloon Swing',
    footprint: { w: 2, h: 2 },
    buildPrice: 950,
    monthlyOperatingCost: 90,
    ticketPrice: 5,
    capacity: 12,
    category: 'fun',
    appeal: 72,
    requiredExcitement: 18,
    rideTicks: 42,
    nauseaGain: 9,
    color: '#ff6b6b',
    icon: '🎈',
  },
  {
    id: 16,
    name: 'Park Train',
    footprint: { w: 1, h: 1 },
    buildPrice: 900,
    monthlyOperatingCost: 80,
    ticketPrice: 4,
    capacity: 20,
    category: 'relax',
    appeal: 65,
    requiredExcitement: 5,
    rideTicks: 50,
    nauseaGain: 1,
    color: '#2e7d32',
    icon: '🚂',
  },
  {
    id: 15,
    name: 'River Cruise',
    footprint: { w: 3, h: 2 },
    buildPrice: 1400,
    monthlyOperatingCost: 120,
    ticketPrice: 6,
    capacity: 14,
    category: 'relax',
    appeal: 78,
    requiredExcitement: 8,
    rideTicks: 55,
    nauseaGain: 2,
    color: '#4dabf7',
    icon: '⛵',
  },
  {
    id: 17,
    name: 'Balloon Stand',
    footprint: { w: 1, h: 1 },
    buildPrice: 180,
    monthlyOperatingCost: 16,
    ticketPrice: 2,
    capacity: 5,
    category: 'fun',
    appeal: 58,
    requiredExcitement: 0,
    rideTicks: 10,
    nauseaGain: 0,
    color: '#ff6b9f',
    icon: '🎈',
  },
  {
    id: 18,
    name: 'Information Stand',
    footprint: { w: 1, h: 1 },
    buildPrice: 210,
    monthlyOperatingCost: 18,
    ticketPrice: 3,
    capacity: 5,
    category: 'relax',
    appeal: 42,
    requiredExcitement: 0,
    rideTicks: 10,
    nauseaGain: 0,
    color: '#5dade2',
    icon: 'ℹ️',
  },
  // ── Food Stalls ──
  {
    id: 8,
    name: 'Burger Stand',
    footprint: { w: 1, h: 1 },
    buildPrice: 200,
    monthlyOperatingCost: 25,
    ticketPrice: 3,
    capacity: 4,
    category: 'food',
    appeal: 60,
    requiredExcitement: 0,
    rideTicks: 15,
    nauseaGain: 0,
    color: '#d35400',
    icon: '🍔',
  },
  {
    id: 9,
    name: 'Pizza Cart',
    footprint: { w: 1, h: 1 },
    buildPrice: 250,
    monthlyOperatingCost: 28,
    ticketPrice: 4,
    capacity: 4,
    category: 'food',
    appeal: 65,
    requiredExcitement: 0,
    rideTicks: 15,
    nauseaGain: 0,
    color: '#e74c3c',
    icon: '🍕',
  },
  // ── Drink Stalls ──
  {
    id: 10,
    name: 'Lemonade Stand',
    footprint: { w: 1, h: 1 },
    buildPrice: 150,
    monthlyOperatingCost: 18,
    ticketPrice: 2,
    capacity: 6,
    category: 'drink',
    appeal: 55,
    requiredExcitement: 0,
    rideTicks: 10,
    nauseaGain: 0,
    color: '#f1c40f',
    icon: '🍋',
  },
  {
    id: 11,
    name: 'Ice Cream Cart',
    footprint: { w: 1, h: 1 },
    buildPrice: 200,
    monthlyOperatingCost: 22,
    ticketPrice: 3,
    capacity: 5,
    category: 'drink',
    appeal: 70,
    requiredExcitement: 0,
    rideTicks: 12,
    nauseaGain: 0,
    color: '#ecf0f1',
    icon: '🍦',
  },
  // ── Toilets ──
  {
    id: 12,
    name: 'Restroom',
    footprint: { w: 1, h: 1 },
    buildPrice: 300,
    monthlyOperatingCost: 10,
    ticketPrice: 1,
    capacity: 4,
    category: 'toilet',
    appeal: 40,
    requiredExcitement: 0,
    rideTicks: 8,
    nauseaGain: 0,
    color: '#bdc3c7',
    icon: '🚻',
  },
  {
    id: 13,
    name: 'Porta-Potty',
    footprint: { w: 1, h: 1 },
    buildPrice: 100,
    monthlyOperatingCost: 5,
    ticketPrice: 0,
    capacity: 2,
    category: 'toilet',
    appeal: 20,
    requiredExcitement: 0,
    rideTicks: 8,
    nauseaGain: 0,
    color: '#2ecc71',
    icon: '🚽',
  },
];

export default ATTRACTIONS;
